// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwrkxjbjxtctydwxxukj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53cmt4amJqeHRjdHlkd3h4dWtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMTQ1MDQsImV4cCI6MjA3Mjg5MDUwNH0.kMUfhoQ1xB2R8vJZW-lsAlI22Si_lFtjzl5jlcyBoc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});